spring:
  application:
    name: halpme

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/halpme?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: 1234
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#    open-in-view: true # 영속성 컨택스트 유지 (Lazy Loading)