name: Halpme CD

on:
  workflow_run:
    workflows: [ "Halpme CI" ]
    types:
      - completed
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy-to-ec2:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Pull Latest Docker Image
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/halpme_cicd_action:latest

      - name: Stop and Remove Old Container
        run: |
          if [ "$(docker ps -q -f name=halpme)" ]; then
            sudo docker stop halpme
            sudo docker rm halpme
          fi

      - name: Run New Container
        run: |
          sudo docker run --name halpme --rm -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/halpme_cicd_action:latest

      - name: Prune Unused Docker Images
        run: sudo docker system prune -f